services:
  web:
    mem_limit: 64m
    image: screeny05/letterboxd-list-radarr:latest
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
  redis:
    mem_limit: 64m
    image: redis:6.0
    restart: unless-stopped
