services:
  mqtt:
    image: eclipse-mosquitto:latest
    container_name: mqtt
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - /home/lestar/_volumes/mqtt/config:/mosquitto/config
      - /home/lestar/_volumes/mqtt/data:/mosquitto/data
      - /home/lestar/_volumes/mqtt/log:/mosquitto/log
    environment:
      TZ: Europe/Stockholm
