services:
  dockhand:
    mem_limit: 336m
    image: fnsys/dockhand:latest
    container_name: dockhand
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Stockholm
    ports:
      - 3005:3000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/lestar/_volumes/dockhand/data:/app/data
      - /home/lestar/containers:/stacks
      - /home/lestar/backup-sources/:/stacks-remote
