services:
  bazarr:
    mem_limit: 832m
    image: linuxserver/bazarr:1.5.6
    container_name: bazarr
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Stockholm
      - UMASK_SET=022
    ports:
      - 6767:6767
    volumes:
      - /home/lestar/_volumes/bazarr/config:/config
      - /media:/media
