services:
  ofelia:
    mem_limit: 96m # peak 7d +20%
    image: mcuadros/ofelia:latest
    container_name: ofelia-scheduler
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command: daemon --docker
