services:
  redis:
    mem_limit: 64m
    image: redis:8.10.1-alpine
    container_name: socials-to-telegram-redis
    restart: unless-stopped
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes

  bot:
    mem_limit: 80m # peak 7d +20%
    image: ghcr.io/liamniou/socials-to-telegram:sha-8294680@sha256:62adf1fe4b421276769739e248f65871128572e756ba1561e7576bdf2817c933
    container_name: socials-to-telegram-bot
    restart: unless-stopped
    environment:
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      REDIS_HOST: redis
      REDIS_PORT: "6379"
    volumes:
      - /home/lestar/_volumes/socials-to-telegram/cookies.txt:/app/cookies.txt
    depends_on:
      - redis

  worker:
    mem_limit: 144m # peak 7d +20%
    image: ghcr.io/liamniou/socials-to-telegram:sha-8294680@sha256:62adf1fe4b421276769739e248f65871128572e756ba1561e7576bdf2817c933
    container_name: socials-to-telegram-worker
    restart: unless-stopped
    command: ["worker.py"]
    environment:
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      REDIS_HOST: redis
      REDIS_PORT: "6379"
    volumes:
      - /home/lestar/_volumes/socials-to-telegram/cookies.txt:/app/cookies.txt
    depends_on:
      - redis

  metrics:
    mem_limit: 64m
    image: ghcr.io/liamniou/socials-to-telegram:sha-8294680@sha256:62adf1fe4b421276769739e248f65871128572e756ba1561e7576bdf2817c933
    container_name: socials-to-telegram-metrics
    restart: unless-stopped
    command: ["metrics.py"]
    ports:
      - "9090:9090"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: "6379"
      METRICS_PORT: "9090"
    depends_on:
      - redis

volumes:
  redis-data:
