services:
  homeassistant:
    mem_limit: 736m # peak 7d +20%
    image: ghcr.io/home-assistant/home-assistant:2026.7.2
    container_name: homeassistant
    restart: unless-stopped
    network_mode: host
    privileged: true
    environment:
      TZ: Europe/Stockholm
    volumes:
      - /home/lestar/_volumes/homeassistant/config:/config
      - /etc/localtime:/etc/localtime:ro
      - /home/lestar/_volumes/homeassistant/hacs_install.sh:/hacs_install.sh:ro
    command:
      - bash
      - -c
      - "/hacs_install.sh && python -m homeassistant --config /config"
