services:
  dockhand:
    image: fnsys/dockhand:latest
    container_name: dockhand
    restart: unless-stopped
    environment:
      TZ: Europe/Stockholm
    ports:
      - "3005:3000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/lestar/_volumes/dockhand/data:/app/data
