services:
  zigbee2mqtt:
    mem_limit: 144m # peak 7d +20%
    image: koenkk/zigbee2mqtt:2.12.1
    container_name: zigbee2mqtt
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - /home/lestar/_volumes/zigbee2mqtt/data:/app/data
    environment:
      TZ: Europe/Stockholm
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
