services:
  sonarr:
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Stockholm
    healthcheck:
      interval: 1h
      retries: 3
      test:
        - CMD
        - ls
        - -al
        - /mnt
      timeout: 10s
    image: linuxserver/sonarr:4.0.17.2952-ls311
    ports:
      - 8989:8989
    restart: always
    volumes:
      - /home/lestar/_volumes/sonarr/configs:/config
      - /media:/media
