services:
  profilarr:
    image: santiagosayshey/profilarr:v1.1.4
    container_name: profilarr
    ports:
      - 6868:6868
    volumes:
      - /home/lestar/_volumes/profilarr/configs:/config
    environment:
      - TZ=Europe/Stockholm
    restart: unless-stopped
