services:
  calibre-web:
    mem_limit: 640m # raised: was OOM-killed
    image: lscr.io/linuxserver/calibre-web:latest
    container_name: calibre-web
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - DOCKER_MODS=linuxserver/mods:universal-calibre
    volumes:
      - /home/lestar/_volumes/calibre-web/config:/config
      - /home/lestar/_volumes/calibre-web/books:/books
    ports:
      - "8083:8083"
    restart: unless-stopped
